const Slider = () => {
	const sliderTextHoverClasses = 'hover:text-fuchsia-500';

	return (
		<section className="slide-track w-full overflow-hidden bg-fuchsia-200 py-7 text-5xl font-bold uppercase text-fuchsia-300">
			<div className="flex w-[200%] ">
				<div className="slide-item flex w-1/2 animate-slide justify-around">
					<a
						target="_blank"
						href="https://github.com/LoyalEnv0y"
						className={sliderTextHoverClasses}
					>
						GitHub
					</a>
					<a
						target="_blank"
						href="https://www.linkedin.com/in/%C3%A7etin-tekin-loyalenv0y/"
						className={sliderTextHoverClasses}
					>
						Linkedin
					</a>
					<a
						target="_blank"
						href="https://www.instagram.com/cetin.tekinn/"
						className={sliderTextHoverClasses}
					>
						Instagram
					</a>
					<a
						target="_blank"
						href="https://www.reddit.com/user/LoyalEnvoy"
						className={sliderTextHoverClasses}
					>
						Reddit
					</a>
					<a
						target="_blank"
						href="https://github.com/LoyalEnv0y"
						className={sliderTextHoverClasses}
					>
						GitHub
					</a>
					<a
						target="_blank"
						href="https://www.linkedin.com/in/%C3%A7etin-tekin-loyalenv0y/"
						className={sliderTextHoverClasses}
					>
						Linkedin
					</a>
					<a
						target="_blank"
						href="https://www.instagram.com/cetin.tekinn/"
						className={sliderTextHoverClasses}
					>
						Instagram
					</a>
					<a
						target="_blank"
						href="https://www.reddit.com/user/LoyalEnvoy"
						className={sliderTextHoverClasses}
					>
						Reddit
					</a>
				</div>
				<div className="slide-item flex w-1/2 animate-slide justify-around ">
					<a
						target="_blank"
						href="https://github.com/LoyalEnv0y"
						className={sliderTextHoverClasses}
					>
						GitHub
					</a>
					<a
						target="_blank"
						href="https://www.linkedin.com/in/%C3%A7etin-tekin-loyalenv0y/"
						className={sliderTextHoverClasses}
					>
						Linkedin
					</a>
					<a
						target="_blank"
						href="https://www.instagram.com/cetin.tekinn/"
						className={sliderTextHoverClasses}
					>
						Instagram
					</a>
					<a
						target="_blank"
						href="https://www.reddit.com/user/LoyalEnvoy"
						className={sliderTextHoverClasses}
					>
						Reddit
					</a>
					<a
						target="_blank"
						href="https://github.com/LoyalEnv0y"
						className={sliderTextHoverClasses}
					>
						GitHub
					</a>
					<a
						target="_blank"
						href="https://www.linkedin.com/in/%C3%A7etin-tekin-loyalenv0y/"
						className={sliderTextHoverClasses}
					>
						Linkedin
					</a>
					<a
						target="_blank"
						href="https://www.instagram.com/cetin.tekinn/"
						className={sliderTextHoverClasses}
					>
						Instagram
					</a>
					<a
						target="_blank"
						href="https://www.reddit.com/user/LoyalEnvoy"
						className={sliderTextHoverClasses}
					>
						Reddit
					</a>
				</div>
			</div>
		</section>
	);
};

export default Slider;
